### ISSUE TITLE
python魔方还原的代码一直出不来最终结果怎么办？

### ISSUE THREAD

**Issue by Yep-Z** [RexWzh/rubik_cube.py#3]
一开始看见博主的这个程序挺感兴趣的，就贴过来研究了一下，代码方面没啥问题，就是运行的时候总是到cube.auto_solve_cube(wait=False)这一步就会报错后面的也没法显示出来，好无奈，只好来向博主求教！
<img width="544" alt="1" src="https://user-images.githubusercontent.com/125191866/218316286-09c3eb63-0bbc-487f-a598-4c94cf2b9ae8.png">
魔方转动的过程中，发现开始转动的方位不准确，为什么会这样呢？可能就是刚开始识别的鼠标位置不准确才导致后面的程序无法执行，可是代码也没有问题啊？麻烦博主看一下是哪里的问题啊！

**Comment by RexWzh** [comment]
> 一开始看见博主的这个程序挺感兴趣的，就贴过来研究了一下，代码方面没啥问题，就是运行的时候总是到cube.auto_solve_cube(wait=False)这一步就会报错后面的也没法显示出来，好无奈，只好来向博主求教！

感谢支持 😆 

> 魔方转动的过程中，发现开始转动的方位不准确，为什么会这样呢？可能就是刚开始识别的鼠标位置不准确才导致后面的程序无法执行，可是代码也没有问题啊？麻烦博主看一下是哪里的问题啊！

我更新了 `demo/demo-jupyter.ipynb` 文件。你可以跟着运行，排查这几种情况：
- `show_detection` 检查魔方定位是否准确
- `check_basic_moves` 检查自动化模块是否正常
- 颜色识别问题：因不同系统颜色值误差，导致状态读取错误

比如，如果检测错误，可以通过下边代码调整识别范围和精度
```py
import scale_match
scale_match.min_scale = 0.8 # 图像较小时调低，默认 0.8
scale_match.max_scale = 3.5 # 图像较大时调高，默认 3.0
scale_match.num_step = 80 # 匹配细度，默认 50 步
```

**Comment by Yep-Z** [comment]
好的，看见博主更新了程序，我再调试调试，感谢博主耐心的回答！

**Comment by Yep-Z** [comment]
博主，在调试的过程中发现，鼠标在检测小面颜色分布那里，鼠标移动获取颜色分布不准确，就是鼠标没有正确的提取一小面中的三行的颜色，这个是识别范围和精度的问题吗？

**Comment by RexWzh** [comment]
> 鼠标没有正确的提取一小面中的三行的颜色，这个是识别范围和精度的问题吗？

确认这步的红线框位置正确，就可以排除检测定位问题。可能是颜色识别了，如果是这样，我晚会写个补丁。
<img width="689" alt="截屏2023-02-14 23 07 22" src="https://user-images.githubusercontent.com/62223937/218777293-3b32bb41-1062-48e1-ac8f-abe3f40f1673.png">

**Comment by Yep-Z** [comment]
https://user-images.githubusercontent.com/125191866/218749660-1f97ccae-39db-4baf-9433-009dd1452489.mp4

谢谢博主答复~ 红线框那里是正确的，就是有点鼠标拖拽的方向错位了，另外“正在检查的面”和“当前正在旋转的面”也都有鼠标拖拽错位了，还有检查鼠标移动中心位置那里貌似是没反应。

<img width="459" alt="11" src="https://user-images.githubusercontent.com/125191866/218751667-95b00ab4-f1ad-405b-8fba-c4e4cf056eb7.png">

辛苦博主再看一下是哪里的问题

**Comment by RexWzh** [comment]
**图像定位**的问题

正常的红框是紧凑的，参考上图。可能是你的魔方页面小了，可以适当调低参数，比如
```py
from rubik import *
import scale_match
# 修改匹配细度（根据需要可以再调整）
scale_match.min_scale = 0.4 # 图像较小时调低，默认 0.8
scale_match.max_scale = 3.0 # 图像较大时调高，默认 3.0
scale_match.num_step = 100 # 匹配细度，默认 50 步
# 识别魔方并查看检测结果
cube = Cube()
cube.show_detection(openwindow=True)
# 还原魔方
cube.auto_solve_cube(wait=False)
```

另外，匹配过程可以通过下边代码来查看(git pull 更新代码）：
```julia
from rubik import *
from video import *

# Get frames
cube = Cube()
images = detect_image(cube.image, template, frames=True)
frames = [cv2PIL(img[1]) for img in images]

# export video
vid_name, vid_comp = "video.mp4", "video_comp.mp4"
imgs_to_video(frames, vid_name, fps=10)
display_video(vid_name, vid_comp)
```

https://user-images.githubusercontent.com/62223937/218944713-a5990a62-e118-4202-9bbd-1a133291e24c.mp4

---

(可选)建议用 Jupyter 运行 `demo/demo-jupyter.ipynb` 进行调试。另一个 Jupyter 文件对应 B 站的视频教程 https://www.bilibili.com/video/BV1yU4y1B71P
```bash
pip install jupyter # 安装 Jupter
jupyter-notebook # 打开 Jupyter
```

**Comment by Yep-Z** [comment]
收到反馈了，谢谢博主，我再调试调试！

**Comment by Yep-Z** [comment]
> **图像定位**的问题
> 
> 正常的红框是紧凑的，参考上图。可能是你的魔方页面小了，可以适当调低参数，比如
> 
> ```python
> from rubik import *
> import scale_match
> # 修改匹配细度（根据需要可以再调整）
> scale_match.min_scale = 0.4 # 图像较小时调低，默认 0.8
> scale_match.max_scale = 3.0 # 图像较大时调高，默认 3.0
> scale_match.num_step = 100 # 匹配细度，默认 50 步
> # 识别魔方并查看检测结果
> cube = Cube()
> cube.show_detection(openwindow=True)
> # 还原魔方
> cube.auto_solve_cube(wait=False)
> ```
> 
> 另外，匹配过程可以通过下边代码来查看(git pull 更新代码）：
> 
> ```julia
> from rubik import *
> from video import *
> 
> # Get frames
> cube = Cube()
> images = detect_image(cube.image, template, frames=True)
> frames = [cv2PIL(img[1]) for img in images]
> 
> # export video
> vid_name, vid_comp = "video.mp4", "video_comp.mp4"
> imgs_to_video(frames, vid_name, fps=10)
> display_video(vid_name, vid_comp)
> ```
> 
> (可选)建议用 Jupyter 运行 `demo/demo-jupyter.ipynb` 进行调试。另一个 Jupyter 文件对应 B 站的视频教程 https://www.bilibili.com/video/BV1yU4y1B71P
> 
> ```shell
> pip install jupyter # 安装 Jupter
> jupyter-notebook # 打开 Jupyter
> ```

哇哦~ 博主好强啊！这是又更新了代码了，我去研究研究~

**Comment by RexWzh** [comment]
增加了展示图像检测过程的工具。

我看你 fork 了仓库，可以点 sync fork 同步更新，本地再用 git pull。去年这个点我也是 GitHub 小白哈哈

![05289FBC-38E8-4B72-90AF-546468096CC3](https://user-images.githubusercontent.com/62223937/219065986-c7caffdd-136a-4e58-955b-f9f364f7936d.jpeg)

**Comment by Yep-Z** [comment]
> 

收到啦~目前GetHub还没玩明白，很多地方好奇就会去点进去看看

**Comment by Yep-Z** [comment]
调试了好久程序，jupyter确实好用啊，前面拿来运行单行代码确实可以排错，后面我在python那里修改了一些错误代码，jupyter运行就会报错了，有两种错误：

<img width="360" alt="1" src="https://user-images.githubusercontent.com/125191866/219389531-49f65d4a-e3ca-4cfc-8f20-af97c45f94ea.png">

这个魔方中心颜色当时是正常的白红蓝没错，但还是有问题。

我又在python那里运行了下代码，也是同样的问题：
<img width="468" alt="4" src="https://user-images.githubusercontent.com/125191866/219390246-89396b46-97b5-488a-8e72-0e6565c4ffba.png">

另一个就是，提示ModuleNotFoundError，这个问题我百度找了还是没解决好：

<img width="445" alt="2" src="https://user-images.githubusercontent.com/125191866/219391060-2e6a071d-fdc7-4e0f-a438-8bb0becad47a.png">

<img width="489" alt="3" src="https://user-images.githubusercontent.com/125191866/219391365-5bb9dba2-b9fb-4c3e-a31a-88bd11030a64.png">

博主抽空看一下~

**Comment by RexWzh** [comment]
> 另一个就是，提示ModuleNotFoundError，这个问题我百度找了还是没解决好：
> 
> <img width="445" alt="2" src="https://user-images.githubusercontent.com/125191866/219391060-2e6a071d-fdc7-4e0f-a438-8bb0becad47a.png">
> 
> <img width="489" alt="3" src="https://user-images.githubusercontent.com/125191866/219391365-5bb9dba2-b9fb-4c3e-a31a-88bd11030a64.png">
> 
> 博主抽空看一下~

第二个，文件名是 rubik.py，进入目录后用 import rubik 导入。
这里你改了代码导致出错。如果修改不重要可以 git reset --hard 重置，如果要给代码添加内容，建议新建一个分支进行，不要污染主分支的代码。

（当前还在更新，版本稳定后我再捣鼓写成模块，这样能通过 pip 安装。）

**Comment by RexWzh** [comment]
> 调试了好久程序，jupyter确实好用啊，前面拿来运行单行代码确实可以排错，后面我在python那里修改了一些错误代码，jupyter运行就会报错了，有两种错误：
> 
> <img alt="1" width="360" src="https://user-images.githubusercontent.com/125191866/219389531-49f65d4a-e3ca-4cfc-8f20-af97c45f94ea.png">
> 
> 这个魔方中心颜色当时是正常的白红蓝没错，但还是有问题。

第一个，确保前几步排错没问题（比如之前提的图像位置），运行代码后，魔方是不是自动切换到后边，再切回来。如果是颜色问题，等这个 PR https://github.com/RexWzh/rubik_cube.py/pull/6 合并后可以搞定。

**Comment by Yep-Z** [comment]
> 

这个排错就图像位置已经可以了，是贴合的了，后边魔方旋转也OK，中心位置的识别也没问题了。

**Comment by Yep-Z** [comment]
> 

好的，谢谢！过会我修改导入试试看，改了一点点代码只是在python上改的，没在GetHub这里应该不会影响主分支吧？

**Comment by RexWzh** [comment]
> > 
> 
> 好的，谢谢！过会我修改导入试试看，改了一点点代码只是在python上改的，没在GetHub这里应该不会影响主分支吧？

不会影响 Github 的代码，非仓库管理者可以通过 Pull Request 的方式提交更改建议，参与代码贡献。

另外， 我刚找到这个 Bug 出在哪：pyautogui 截图坐标和操作坐标不匹配，比如我这边运行：
```py
import pyautogui as pg
print(pg.size(), pg.screenshot().size)
# Size(width=1470, height=956) (2940, 1912)
```
二者不匹配，导致采样跑到魔方的白色区域，颜色识别错误。

问题修复已经通过这个 PR https://github.com/RexWzh/rubik_cube.py/pull/9 进行了修复，你可以更新主分支来重新测试。


Ref: https://stackoverflow.com/questions/45302681/running-pyautogui-on-a-different-computer-with-different-resolution

**Comment by RexWzh** [comment]
这个仓库我按 Python 包的规范进行了重写。demo 用的 Jupyter 文件都删了，只保留代码。当前版本稳定后，我应该会把演示文件放 `demo` 分支。

当前可以通过下边代码调用还原工具
```py
# 进入 <仓库主目录>
from rubik import *
from rubik.tools import expand_cube
cube = Cube()
# cube.show_detection()
state = cube.get_cube_distribution(string_code=True)
# 检查展开图
print(expand_cude(state))
cube.auto_solve_cube(wait=False)
```

**Comment by Yep-Z** [comment]
> > > 
> > 
> > 
> > 好的，谢谢！过会我修改导入试试看，改了一点点代码只是在python上改的，没在GetHub这里应该不会影响主分支吧？
> 
> 不会影响 Github 的代码，非仓库管理者可以通过 Pull Request 的方式提交更改建议，参与代码贡献。
> 
> 另外， 我刚找到这个 Bug 出在哪：pyautogui 截图坐标和操作坐标不匹配，比如我这边运行：
> 
> ```python
> import pyautogui as pg
> print(pg.size(), pg.screenshot().size)
> # Size(width=1470, height=956) (2940, 1912)
> ```
> 
> 二者不匹配，导致采样跑到魔方的白色区域，颜色识别错误。
> 
> 问题修复已经通过这个 PR #9 进行了修复，你可以更新主分支来重新测试。
> 
> Ref: https://stackoverflow.com/questions/45302681/running-pyautogui-on-a-different-computer-with-different-resolution

博主敬业啊！我之前也注意到关于采样坐标的问题，只是不太确定。多谢博主的调试，我再去琢磨一下~

**Comment by RexWzh** [comment]
搞定的话我把这个 issue 关了。

---

当前加入了颜色更新功能
```py
cube = Cube(updatecolor=True, checkcolor=True)
cube.auto_solve_cube(wait=False)
```

通过插件右下角可以选择其他色系的魔方，比如
<img width="238" alt="截屏2023-02-19 23 32 04" src="https://user-images.githubusercontent.com/62223937/219958139-ea6f373d-9a39-4ce8-b632-c7f297c9f499.png">
